sonar.projectKey=Tether
sonar.sources=backend/app,frontend/src,scripts
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=frontend/coverage/**,frontend/dist/**,frontend/src/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.html
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
